### ISSUE TITLE
Action on dismiss

### ISSUE THREAD

**Issue by dejiapps** [maltaisn/icondialoglib#11]
If I wanted to have something done when the icon dialog is dismissed, how would I go about doing that?

Thanks for the great library by the way.

**Comment by maltaisn** [comment]
There's currently no way to set a dismiss listener. However, I think you could try doing this when creating the icon dialog:
```java
IconDialog dialog = new IconDialog() {
    @Override
    public void onDismiss(@NonNull DialogInterface dialog) {
        super.onDismiss(dialog)
        // Do your stuff here
    }
}
```
If that doesn't work I'll add a dismiss listener.

**Comment by dejiapps** [comment]
I tried it but it didn't work unfortunately.

**Comment by maltaisn** [comment]
I'll add the listener then, a new release should be available in a few days.

**Comment by maltaisn** [comment]
I added the listener in 2.3.0, you can use it just like the icon selection callback.
