### ISSUE TITLE
Adding more icons

### ISSUE THREAD

**Issue by maltaisn** [maltaisn/icondialoglib#12]
Nearly all icons of the library come from the [material design icons](https://github.com/Templarian/MaterialDesign) repository. The maintainers of the project keep adding new icons every week, but I only add the most relevant ones. This library started with 976 icons and there are 1045 as of v2.3.0.

I could add a lot more icons that don't currently have an equivalent in the library, but will this be a problem? 
- For users, more icons mean it takes more time to search by scrolling through the list. Also the loading time of the dialog gets longer.
- The app size will also be increased, each new icon adds on average 150 bytes to the XML file without counting the additional labels, for a total of ~140kB currently. 
- Translation will become an even longer task.

Should I add more icons?

**Comment by guger** [comment]
I think those icons are enough, especially since every user could add his own icons!
