### ISSUE TITLE
Pass dialog instance to onIconDialogIconsSelected

### ISSUE THREAD

**Issue by dirkam** [maltaisn/icondialoglib#17]
Would it be possible for you to change `onIconDialogIconsSelected` so it has the dialog arguments/instance as a parameter?

I'd like to show icons in a `RecyclerView`. When the user clicks on the icon it should open the icon dialog to set/change it and on the callback I'd like to know which item was clicked on so the list can be updated. I was planning to use `setArguments()` and `getArguments()` to set the ID of the item or something like that.

**Comment by maltaisn** [comment]
Yes I can add that parameter.

I would suggest just saving the position of the clicked icon in your fragment/activity/presenter/etc and use it to change the drawable when an icon is selected.

**Comment by dirkam** [comment]
Sure, there are workarounds for this but with that parameter, it could be much simpler and cleaner, I guess. Thanks for considering this.

**Comment by maltaisn** [comment]
This is added in v2.4.0

**Comment by dirkam** [comment]
Thank you.
