### ISSUE TITLE
SVGs do not scale

### ISSUE THREAD

**Issue by TheXplore** [maltaisn/icondialoglib#19]
When adding a custom icon, the svg is not scalled to the size of the container.

The customicons.xml (zipped, because Github requires it):
[icons.zip](https://github.com/maltaisn/icondialoglib/files/3004235/icons.zip)

The path is relativly huge, but it should not be a problem for the lib to scale it to the default 50dp.

Thanks for this awesome lib ;)

![Screenshot](https://user-images.githubusercontent.com/26611093/54934723-47481e80-4f1f-11e9-8b64-fe7984b6a6a4.png)

**Comment by maltaisn** [comment]
The library doesn't scale any icon, it assumes they're all 24dp. As you can see there is no size attribute in the icons xml. The size is hardcoded in the binary xml data that you can see in the Icon class. You'll need to resize your icons. I could probably add an optional size attribute, but I don't think that's necessary. Tell me what you think.
