### ISSUE TITLE
ERROR: Failed to resolve: com.maltaisn:iconpack-default:1.0.0

### ISSUE THREAD

**Issue by jrcacd** [maltaisn/icondialoglib#23]

**Comment by maltaisn** [comment]
I uploaded just recently to bintray, it has yet to be linked with jcenter so it's not available for download yet. In the meantime, you can download the aar file directly from bintray (click on the download badge from the readme) and include it in your libs/ folder. 

EDIT: Here's the download link: https://bintray.com/maltaisn/icon-dialog/download_file?file_path=com%2Fmaltaisn%2Ficonpack-default%2F1.0.0%2Ficonpack-default-1.0.0.aar

**Comment by maltaisn** [comment]
It should be available now.
