### ISSUE TITLE
Iconpacks are not available to sync via gradle

### ISSUE THREAD

**Issue by GlitchTech** [maltaisn/icondialoglib#24]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.maltaisn:iconpack-default:1.0.0.

I'm updating from 2.5. to 3.1. The 3.1 dependency works but gradle cannot find the iconpack. I do see the resource on bintray and see the aar in there so I'm not sure what's up.

To confirm, I have the dependencies included as
```
implementation "com.maltaisn:icondialog:3.1.0"
implementation "com.maltaisn:iconpack-default:1.0.0"
```

I tried the other two icon packs listed on the gradle page (com.maltaisn:iconpack-community-material:4.8.95 and com.maltaisn:iconpack-font-awesome:5.12.0) and neither of those worked as well.

I was able to add another random dependency from a different library so I'm not sure what is up. I do see that issue #23 had this problem as well for the default icon pack.

**Comment by maltaisn** [comment]
I'm having the same problem. I tried republishing the icon pack and syncing it to maven but Gradle still can't find it. I'll see if it works tomorrow, maybe one of their servers is down or something. In the meantime you can download the aar file from bintray and put it in your libs/ folder.

**Comment by GlitchTech** [comment]
It still seems down. Odd. Thanks for giving a try. It does seem to be out of your control.

**Comment by monil1334** [comment]
@maltaisn it seems like I cannot load the drawable because I cannot seem to find IconPackDefaultKt even with the downloaded .aar file from the bintray. Is there any other way to initialize the icon packs.

**Comment by maltaisn** [comment]
@monil1334 If you using it from Kotlin, use `createDefaultIconPack` top-level extension function. `IconPackDefaultKt` is only visible and needed from Java. Also make sure you have the following line in your app build script dependencies block:
```groovy
implementation fileTree(dir: "libs/", include: ["*.aar", "*.jar"])
```
aar file is available for download [here](https://bintray.com/maltaisn/icon-dialog/download_file?file_path=com%2Fmaltaisn%2Ficonpack-default%2F1.0.0%2Ficonpack-default-1.0.0.aar).

I'm still trying to find out why the dependency cannot be resolved by gradle.

**Comment by maltaisn** [comment]
It should be fixed, please confirm if it works for you. There was an empty `<dependency/>` tag in the pom file.

**Comment by GlitchTech** [comment]
Just commenting, yes. Issue fixed for me. Thanks.
