### ISSUE TITLE
Icon drawable color changes after using it in dialog

### ISSUE THREAD

**Issue by idrisadetunmbi** [maltaisn/icondialoglib#27]
I am using the icon drawables from the lib before using them in the `IconDialog` and as at this point, the drawables have the default color (black). However, when I use them in the `IconDialog` after the initial point with the `icdIconStyle` specified, the drawable colors outside the dialog are also modified.

```
// iconPack has been loaded on application start
val drawable = iconPack.getIconDrawable(iconId, IconDrawableLoader(view.context))

// drawable has default color (black) here
view.setImageDrawable(drawble)

// with icdIconStyle having a different color (say white) and calling iconDialog.show() 
// later, drawable color in view above is also modified
```

**Comment by maltaisn** [comment]
Thanks. I was already aware of the bug but I thought `Drawable.wrap(iconDrawable).mutate()` had fixed it. Actually I had to call `drawable.constantState.newDrawable()` to make sure no drawables obtained share the same state. So this is fixed in v3.1.1.
