### ISSUE TITLE
Typo in ExampleApplication documentation

### ISSUE THREAD

**Issue by OscarCaro** [maltaisn/icondialoglib#30]
I found an error in the Example Application in your documentation (at https://github.com/maltaisn/icondialoglib/wiki/Example-application ).
In the Java version, in app.Java there's this function: 

    private void loadIconPack() {
        // Create an icon pack loader with application context.
        IconPackLoader loader = new IconPackLoader(this);

        // Create an icon pack and load all drawables.
        iconPack = IconPackDefault.createDefaultIconPack(loader);
        iconPack.loadDrawables(loader.getDrawableLoader());

        return iconPack;
    }

This method shouldn't return the iconPack.

**Comment by OscarCaro** [comment]
**Old**: I found another error, now in the mainActivity.java. 

```
@Nullable
@Override
public IconPack getIconDialogIconPack() {
    return ((App) getApplication()).getIconPack();
}
```
 I don't quite understand the kotlin version of this function, so I cannot solve the issue. The call to getApplication returns the instance of the global application, and so when you cast it to App it throws a ClassCastException.
I guess that what this function is supposed to do is to get the IconPack variable stored in App activity, but to do so it must have an object of that activity.
Furthermore, the name of this function doesn't match any of the methods in the callback interface it is overriding.
Thanks.

**Edit**: The problem was way deeper than it seemed
1st: I didn't understand the implications of the App.java extending Application. Now I know that's meant to let the class be alive through the whole app lifecycle, and to keep global data
2nd: It wasn't specified in the instructions that for a class to extend Application, the manifest should be modified (the android::name of the <application/> should be modified to the class path)
3rd: There was a typo in my implementation of the iconPack.xml, so when the above was fixed it still didn't launch the app correctly.

I'm not deleting this whole comment just in case someone goes through the same problems.

**Comment by maltaisn** [comment]
I fixed the typo and added a paragraph to explain why the icon pack is loaded in the Application class.
