### ISSUE TITLE
Get drawable after selection

### ISSUE THREAD

**Issue by Ahsan221B** [maltaisn/icondialoglib#33]
I am using version `3.2.0` in Java-based activity. The user can only select one icon at a time. How do I get a drawable/image of that selected icon in the method `onIconDialogIconsSelected`? I want to display the selected icon in an image view.

**Comment by maltaisn** [comment]
Just use `Icon.getDrawable()` if the icons are already loaded (which is the case if they were shown in the dialog). This wil return a drawable that you can set on your image view. 

You can also use `IconPack.getIconDrawable(id, loader)` if you're not sure if the icon pack is fully loaded yet, for example on application startup.
