### ISSUE TITLE
Implementation 

### ISSUE THREAD

**Issue by HyperionElectronicsCo** [maltaisn/icondialoglib#38]
I need to use this pre 2.1.0, how do I go about implementing this
Kind regards

**Comment by maltaisn** [comment]
What do you mean pre 2.1.0? Android SDK <7? That would hardly be possible, AppCompat and Material Components only support API 14 and above and the library relies on both. Or did you mean the library version?

**Comment by HyperionElectronicsCo** [comment]
Version 2.1.0 and above use AndroidX libraries.

My app doesn't use androidx, I'm still pre androidx as I'm coding using just my phone 

I'm writing an IDE and need to impliment an icon picker

**Comment by HyperionElectronicsCo** [comment]
implementation 'com.maltaisn:icondialog:2.0.2'

**Comment by maltaisn** [comment]
Yes v2.0.2 and before don't use AndroidX, that should work. You can view [the repository at that version](https://github.com/maltaisn/icondialoglib/tree/v2.0.2) to see the code. The wiki also has past revisions available if that helps.
