### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by mihir20** [maltaisn/icondialoglib#4]
What if we want to change color of icons ?

**Comment by maltaisn** [comment]
There are two attributes that can be used to change the color of icons. You can look at the wiki page for [Styling the dialog](https://github.com/maltaisn/icondialoglib/wiki/Styling-the-dialog) which explains how to use them. The two attributes are:

- `icdIconColor`: Icon color when not selected. Default is `?android:attr/textColorSecondary`.
- `icdSelectedIconColor`: Icon color when selected. Default is `?attr/colorAccent`.

**Comment by mihir20** [comment]
I want to use icon in my ImageView and change the icon color when some change happens or when i click a button.

**Comment by maltaisn** [comment]
You can set a color filter on the ImageView like this:
```java
Icon icon = IconHelper.getInstance(context).getIcon(232);  // Get an icon
imageView.setImageDrawable(icon.getDrawable(context));     // Set the icon on the image view
imageView.setColorFilter(color, PorterDuff.Mode.SRC_IN);   // Change the icon color
```
Alternatively, you can tint the drawable directly with `icon.getDrawable(context).setColorFilter(color, PorterDuff.Mode.SRC_IN)`. 

Is that what you needed?
