### ISSUE TITLE
How to make large icons ( 3 columns )

### ISSUE THREAD

**Issue by anand-010** [maltaisn/icondialoglib#40]
How to change icons size (column count ).
i am tried by changing width and height <icons width="24" height="24">
that only scales icons not changing column row count.

by giving width 5, height 5 
![WhatsApp Image 2021-03-04 at 12 03 09 PM](https://user-images.githubusercontent.com/32414977/109921608-229b7a80-7ce2-11eb-889d-f49cb75d3c46.jpeg)

**Comment by maltaisn** [comment]
You need to make a custom style in XML for this:
###### styles.xml
```
<style name="CustomIconDialogStyle" parent="IcdStyle">
    <item name="icdIconSize">100dp</item>
</style>
```
Then in your app theme you specify this custom style as the icon dialog style:
###### themes.xml
```
<item name="icdStyle">@style/CustomIconDialogStyle</item>
```
You can check out the [demo app source](https://github.com/maltaisn/icondialoglib/tree/master/app/src/main) if you're unsure where to put what. A `100dp` icon size gave me three column, but keep in mind this will depend on each user device size, some users might see only two columns, others with tablets might see four columns. There's no way to set a fixed amount of columns, only the icon size.
<img src="https://user-images.githubusercontent.com/33690959/109970670-52875580-7cc3-11eb-9033-5fb9f3b6fa07.png" width="500"/>

**Comment by anand-010** [comment]
Thank @maltaisn That worked
![WhatsApp Image 2021-03-05 at 11 23 55 AM](https://user-images.githubusercontent.com/32414977/110074613-820f8e00-7da7-11eb-8b49-967dd2b1a7c1.jpeg)
