### ISSUE TITLE
how to show original icon colors without filter

### ISSUE THREAD

**Issue by anand-010** [maltaisn/icondialoglib#41]

**Comment by maltaisn** [comment]
This can also be done with styles:
###### styles.xml
```
<style name="CustomIconDialogStyle" parent="IcdStyle">
   <item name="icdIconStyle">@style/CustomIconStyle</item>
</style>

<style name="CustomIconStyle" parent="IcdIconStyle">
    <item name="tint">@null</item>
</style>
```
But then there will be no way of knowing which icon is selected. I proposed a solution to this in [another issue](https://github.com/maltaisn/icondialoglib/issues/37#issuecomment-633762015), adding a  border to selected icons.
![image](https://user-images.githubusercontent.com/33690959/109971312-1accdd80-7cc4-11eb-81c7-39000855748e.png)

**Comment by anand-010** [comment]
Thank you @maltaisn Thats worked
![WhatsApp Image 2021-03-05 at 11 23 55 AM](https://user-images.githubusercontent.com/32414977/110074694-a7040100-7da7-11eb-8751-d025c3e58acf.jpeg)
