### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Pmckenna55** [maltaisn/icondialoglib#42]
I have been trying to implement this and copied the example exactly. It does not work. Would more documentation be possible as I am getting **'java.lang.ClassCastException: androidx.multidex.MultiDexApplication cannot be cast to com.example.myTestApp.App'** when I attempt to show the dialog.

_'The icon pack is stored in an Application class (declared in android:name in the manifest) in order to keep it when the activity is destroyed, for example on a configuration change'_ Do I have to add this myself? As I don't see it in the manifest? How would I do that?

**Comment by maltaisn** [comment]
Yes, your custom application class needs to be registered in the manifest, as stated in the [Android documentation](https://developer.android.com/reference/android/app/Application).

```xml
<application
    android:name="com.example.myTestApp.App"
    ...
```
Otherwise the class won't do anything.

**Comment by Pmckenna55** [comment]
Thank you for the reply, it is launching now. 

Could you please tell me how would I save the icon's path to an object? I want to display user-selected icons in a listview.

**Comment by maltaisn** [comment]
Each icon has an integer ID, you can save that. The ID can be used later to get the icon drawable.

**Comment by Pmckenna55** [comment]
Something like: 'mContext.getResources().getDrawable(drawableId)' should work?

**Comment by Pmckenna55** [comment]
IconPack pack = getIconDialogIconPack();
        Icon icor = pack.getIcon(iconID);
        icor.getDrawable();

That seems more like it
