### ISSUE TITLE
Theme.MaterialComponents

### ISSUE THREAD

**Issue by Pmckenna55** [maltaisn/icondialoglib#44]
Switching my app's theme from Theme.MaterialComponents to Theme.AppCompat in styles.xml seems to have turned all the icons pink and shrunk the dialog buttons. Could you please let me know if there is a way to prevent this from happening or do I have to switch back?

**Comment by maltaisn** [comment]
The app relies on attributes such as `colorOnSurface` that come with Material Components. Using Theme.MaterialComponents as a parent sets default values to these attributes. The pink color usually means there was an error resolving a color attribute. The dialog buttons are (iirc) MaterialButtons that come with Marerial Components, thus rely on some of the attributes. You should probably switch back, the library is meant to fit with Material Components theming scheme.

**Comment by Pmckenna55** [comment]
Ok, thanks for the reply.
