### ISSUE TITLE
Accessing icons from layouts

### ISSUE THREAD

**Issue by greencow555** [maltaisn/icondialoglib#45]
So I have the dialog working great (thanks!) and I've saved the id to a JSON file which my layout has access to. 

My question is how do I actually access the icon pack from inside a normal layout object? Everything I try just says the iconpack is null. 

Thanks.

**Comment by maltaisn** [comment]
Did you setup the `App` class to contain the icon pack like in the wiki example? In this case you can access it using the context: 
```java
((App) getContext().getApplicationContext()).getIconPack()
```
If not, then it's hard to say, I'll need more details.

**Comment by BraianS** [comment]
In Kotlin to get icons just use

``` val iconPack = (context.applicationContext as App).iconPack```
