### ISSUE TITLE
Using with Fragments (Icon dialog must have a callback.)

### ISSUE THREAD

**Issue by ahmed-ms** [maltaisn/icondialoglib#46]
I try to use this library with fragment and apply as in example 

`override val iconDialogIconPack: IconPack?
        get() = (requireActivity().application as App).iconPack`

---------

And in onViewCreat
`
 val iconDialog = requireActivity().supportFragmentManager.findFragmentByTag(ICON_DIALOG_TAG) as IconDialog?
            ?: IconDialog.newInstance(IconDialogSettings())

        button_icons.setOnClickListener {
            iconDialog.show(requireActivity().supportFragmentManager, ICON_DIALOG_TAG)
        }
`

when I try click button I have this exception
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mjet, PID: 8467
    java.lang.IllegalStateException: Icon dialog must have a callback.

**Comment by maltaisn** [comment]
Did you implement the callback in your activity or fragment? If you check the example, you'll see that the activity implements the `IconDialog.Callback` interface and the `onIconDialogIconsSelected` method, which is needed to allow the dialog to send results.

**Comment by ahmed-ms** [comment]
I implements in fragment also I implements `IconDialog.Callback` interface and the `onIconDialogIconsSelected` method

**Comment by ahmed-ms** [comment]
It is work now I change `supportFragmentManager` to `childFragmentManager `
Thank you
