### ISSUE TITLE
Download link doesn't work!

### ISSUE THREAD

**Issue by lakpriya-singlifeph** [maltaisn/icondialoglib#47]
download link: https://bintray.com/maltaisn/icon-dialog/download_file?file_path=com%2Fmaltaisn%2Ficonpack-default%2F1.0.0%2Ficonpack-default-1.0.0.aar

it is redirecting to jfrog.com, How can I download the aar?

**Comment by maltaisn** [comment]
I should probably fix that. Don't you use Gradle to get your depencies though?

Here's the correct link: https://oss.sonatype.org/#nexus-search;quick~com.maltaisn
You can select the icondialog row with the version you want, the icon packs are there too. Then select the file in the tree, and click on the Artifact tab on the right pane, there will be a download button there.

**Comment by lakpriya-singlifeph** [comment]
I tried but it does not sync.

getting these errors.

```
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.maltaisn:iconpack-default:1.0.0.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.maltaisn:iconpack-default:1.0.0.
Show Details
Affected Modules: app

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.maltaisn:iconpack-default:1.0.0.
Show Details
Affected Modules: app

```

**Comment by maltaisn** [comment]
Do you have the `mavenCentral()` repository declared?

**Comment by lakpriya-singlifeph** [comment]
Yes. I have, Previously I used ` implementation "com.maltaisn:icondialog:3.1.0"` which gives the error. but with `implementation "com.maltaisn:icondialog:3.3.0"` it syncs as expected. Please update the documentation and wiki page!

**Comment by maltaisn** [comment]
I updated it. Not all versions are in the maven repository, that's probably why it failed.
