### ISSUE TITLE
get icon by id without loading all icons in the pack.

### ISSUE THREAD

**Issue by lakpriya-singlifeph** [maltaisn/icondialoglib#48]
```
    private Drawable loadIcon(int index) {

        // Create an icon pack loader with application context.
        IconPackLoader loader = new IconPackLoader(this);

        // Create an icon pack and load all drawables.
        iconPack = iconPack != null ? iconPack : IconPackDefault.createDefaultIconPack(loader);

        return iconPack.getIconDrawable(index, loader.getDrawableLoader());
    }
```

>>>> Loaded Icons: 1045

Can we have separate memory efficient method to load requested icon only?

**Comment by maltaisn** [comment]
You can use `IconPack.getIconDrawable`:
https://github.com/maltaisn/icondialoglib/blob/c561f68bf302a94626631d1930b88f4faf45528c/lib/src/main/kotlin/com/maltaisn/icondialog/pack/IconPack.kt#L81-L85

The icon will be loaded if it hasn't been already.

**Comment by lakpriya-singlifeph** [comment]
I have used it in my function. Is that function memory efficient?

**Comment by maltaisn** [comment]
Yes it should be fine. You can call it from another thread if you don't want to take any chances, but I doubt loading a single icon takes more than 1-2 ms.

**Comment by lakpriya-singlifeph** [comment]
Can we create a method to load one icon at a time by id? If we can do that it is very efficient!

getIcon(12)

**Comment by maltaisn** [comment]
No you have to load the entire pack to get one icon if that's what you mean. If we're gonna parse the entire XML file we might as well load it fully instead of just loading one icon. You can load a single icon drawable though as I explained previously.
