### ISSUE TITLE
Selecting an icon after searching should hide the virtual keyboard

### ISSUE THREAD

**Issue by ghost** [maltaisn/icondialoglib#6]
## Repro

1. Open the icon dialog
2. Type "carrot"
3. Select the carrot icon

### Expected
The virtual keyboard should close so I can press the `SELECT` button

### Actual
The virtual keyboard stays open, which, on my device, covers the `SELECT` button, requiring an extra step to pick an icon

## Suggestion

Close the virtual keyboard when the user taps anywhere other than the search box.

**Comment by maltaisn** [comment]
Yes you're right, the keyboard is already closed when the Search button of the keyboard is clicked, but not when an icon is selected. I'll change that as soon as possible.

**Comment by maltaisn** [comment]
I changed it in v2.1.0. I also migrated the library to AndroidX, I hope you don't mind.
