### ISSUE TITLE
AndroidX/Material design dialog buttons

### ISSUE THREAD

**Issue by guger** [maltaisn/icondialoglib#9]
Since the dialogs buttons are not part of the dialog, but part of the layout, they are not displayed correctly in Material-Component-Themes. The buttons' background is filled, and not invisible, as it should be.

**Comment by maltaisn** [comment]
I'll see if I can make them part of the dialog.

**Comment by guger** [comment]
I tried migrating to an AlertDialog, but failed due to the button initialization (show/hide/disable) since IconLoader completes before the dialog is shown.

**Comment by maltaisn** [comment]
Actually the reason I'm not using AlertDialog is that it has a very badly designed view hierarchy and it caused performance problem with ConstraintLayout. Sometimes it took as much as 2-3 sec to just open the dialog.

Did you try doing the button initialization in the OnShowListener of the dialog instead? Or you could move the entire IconHelper.LoadCallback to the OnShowListener.

**Comment by guger** [comment]
Okay I'll try!

**Comment by guger** [comment]
Is there a special reason why you show a DialogFragment instead of an AlertDialog?

**Comment by maltaisn** [comment]
I use a fragment to access to `setRetainInstance`, although I think this is a bad practice and I should eventually change it. If you're asking why I use `Dialog` instead of `AlertDialog`, it's for performance as I said earlier.

**Comment by guger** [comment]
I'm getting an IndexOutOfBoundsError on start, when LoadCallback is called on show.
Did you already try something?

**Comment by maltaisn** [comment]
No I didn't commit anything. Paste the stacktrace if you have trouble finding why.

**Comment by guger** [comment]
In my fork (https://github.com/guger/icondialoglib/tree/dev), I'm getting the following error:

> java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
>         at androidx.recyclerview.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:325)
>         at androidx.recyclerview.widget.GridLayoutManager.calculateItemBorders(GridLayoutManager.java:310)
>         at androidx.recyclerview.widget.GridLayoutManager.updateMeasurements(GridLayoutManager.java:281)
>         at androidx.recyclerview.widget.GridLayoutManager.onAnchorReady(GridLayoutManager.java:356)
>         at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:579)
>         at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
>         at com.maltaisn.icondialog.IconLayoutManager.onLayoutChildren(IconLayoutManager.java:49)
>         at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
>         at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
>         at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)

**Comment by maltaisn** [comment]
Maybe try setting the layout manager before the adapter. I really don't see what could be causing the error. Except from changing the Dialog to an AlertDialog and moving the load callback in onShow, did you change anything else?

**Comment by guger** [comment]
All changes are in the "dev" branch, the whole dialog is now in kotlin..

**Comment by guger** [comment]
Issue can be solved by custom themes

**Comment by maltaisn** [comment]
I haven't been doing much Android development for the past few months and I completely missed the AndroidX changes. Are material component themes what everyone use with AndroidX? Should `Widget.MaterialComponents.Button.TextButton.Dialog` be the default button style or it will cause issues for some people not using it? In the last calcdialog release it's what I did so maybe I was wrong.

**Comment by guger** [comment]
Well I closed my pull request due to those concerns..
I think actually there a lot of developers who didn't migrate to material components, but it's the best way to use e.g. Chips, etc.

Since custom theming of the dialog solves the issue, this isn't a problem anymore, just a little hint in the documentation would be important!
